LARGURA_TELA = 800
ALTURA_TELA = 700
TITULO_JANELA = "Defend the ROM"
FPS = 60

TAMANHO_MATRIZ = 8
ALTURA_FILEIRA = 75

SPRITE_ROM_PATH = "sprites/ROM.png"
SPRITE_ROM_TAMANHO = (110, 600)

ROM_VIDA = 2000

MUSICA_FUNDO_PATH = "musicas/musica_fundo.mp3"
MUSICA_VOLUME = 0.4
